### ISSUE TITLE
Why the user must enable auto-save?

### ISSUE THREAD

**Issue by dhonx** [0x9ef/vscode-vlang#75]
https://github.com/0x9ef/vscode-vlang/blob/a8642c0dcf55ab4512b45227c50616458640c1e0/README.md#L26
Sorry, can I know the reason why the user must enable auto-save?  🤔

**Comment by 0x9ef** [comment]
Idk, it's your choose, for me preferred to auto save file without loss after an a editing (like a missclick or another way).

**Comment by dhonx** [comment]
I think if this has no effect on this extension then it would be better to just get rid of it.

**Comment by alexesprit** [comment]
Firstly I thought, it's recommended to turn on autosave, because `v fmt` works with files, not string input, so files should be up-to-dated (and autosave helps to keep files updated). But the formatter saves the current file before formatting, so I was wrong.

If autosave feature is not required for extension work, it should be removed to avoid confusing.
